type IconMap = Record<string, string>;

const faToGoogleMap: IconMap = {
    // Solid Icons
    "fa-solid fa-coffee": "local_cafe",
    "fa-solid fa-heart": "favorite",
    "fa-solid fa-star": "star",
    "fa-solid fa-envelope": "mail",
    "fa-solid fa-search": "search",
    "fa-solid fa-user": "person",
    "fa-solid fa-home": "home",
    "fa-solid fa-cog": "settings",
    "fa-solid fa-check": "check",
    "fa-solid fa-times": "close",
    "fa-solid fa-comment": "comment",
    "fa-solid fa-paper-plane": "send",
    "fa-solid fa-calendar": "calendar_today",
    "fa-solid fa-briefcase": "work",
    "fa-solid fa-folder": "folder",
    "fa-solid fa-camera": "photo_camera",
    "fa-solid fa-music": "music_note",
    "fa-solid fa-gamepad": "sports_esports",
    "fa-solid fa-code": "code",
    "fa-solid fa-globe": "public",
    "fa-solid fa-paint-brush": "brush",
    "fa-solid fa-rocket": "rocket_launch",
    "fa-solid fa-tree": "park",
    "fa-solid fa-lightbulb": "lightbulb",
    "fa-solid fa-coins": "monetization_on",
    "fa-solid fa-thumbs-up": "thumb_up",
    "fa-solid fa-thumbs-down": "thumb_down",
    "fa-solid fa-hourglass": "hourglass_empty",
    "fa-solid fa-key": "key",
    "fa-solid fa-umbrella": "umbrella",
    "fa-solid fa-sun": "light_mode",
    "fa-solid fa-moon": "dark_mode",
    "fa-solid fa-plane": "flight",
    "fa-solid fa-srimp": "set_meal", // Typo in FA list 'srimp', fallback to meal
    "fa-solid fa-bicycle": "directions_bike",
    "fa-solid fa-car": "directions_car",
    "fa-solid fa-bus": "directions_bus",
    "fa-solid fa-train": "train",
    "fa-solid fa-ship": "directions_boat",
    "fa-solid fa-anchor": "anchor",
    "fa-solid fa-microphone": "mic",
    "fa-solid fa-television": "tv",
    "fa-solid fa-magnet": "shopping_bag", // Geen directe magnet, alternatief
    "fa-solid fa-bug": "bug_report",
    "fa-solid fa-heartbeat": "favorite_border",
    "fa-solid fa-gift": "redeem",
    "fa-solid fa-leaf": "eco",
    "fa-solid fa-umbrella-beach": "beach_access",
    "fa-solid fa-bolt": "bolt",
    "fa-solid fa-crown": "workspace_premium",
    "fa-solid fa-bell": "notifications",
    "fa-solid fa-cut": "content_cut",
    "fa-solid fa-copy": "content_copy",
    "fa-solid fa-paste": "content_paste",
    "fa-solid fa-file": "insert_drive_file",
    "fa-solid fa-folder-open": "folder_open",
    "fa-solid fa-chart-bar": "bar_chart",
    "fa-solid fa-chart-line": "show_chart",
    "fa-solid fa-chart-pie": "pie_chart",
    "fa-solid fa-table": "table_chart",
    "fa-solid fa-align-left": "format_align_left",
    "fa-solid fa-align-center": "format_align_center",
    "fa-solid fa-align-right": "format_align_right",
    "fa-solid fa-align-justify": "format_align_justify",
    "fa-solid fa-bold": "format_bold",
    "fa-solid fa-italic": "format_italic",
    "fa-solid fa-underline": "format_underlined",
    "fa-solid fa-strikethrough": "format_strikethrough",
    "fa-solid fa-heading": "title",
    "fa-solid fa-list": "list",
    "fa-solid fa-list-ol": "format_list_numbered",
    "fa-solid fa-list-ul": "format_list_bulleted",
    "fa-solid fa-indent": "format_indent_increase",
    "fa-solid fa-outdent": "format_indent_decrease",
    "fa-solid fa-link": "link",
    "fa-solid fa-unlink": "link_off",
    "fa-solid fa-quote-left": "format_quote",
    "fa-solid fa-quote-right": "format_quote",
    "fa-solid fa-image": "image",
    "fa-solid fa-file-image": "image",
    "fa-solid fa-file-audio": "audio_file",
    "fa-solid fa-file-video": "video_file",
    "fa-solid fa-file-pdf": "picture_as_pdf",
    "fa-solid fa-file-word": "description",
    "fa-solid fa-file-excel": "grid_on",
    "fa-solid fa-file-powerpoint": "slideshow",
    "fa-solid fa-file-archive": "folder_zip",
    "fa-solid fa-file-code": "integration_instructions",
    "fa-solid fa-comment-dots": "chat",
    "fa-solid fa-comments": "forum",
    "fa-solid fa-plus": "add",
    "fa-solid fa-minus": "remove",
    "fa-solid fa-times-circle": "cancel",
    "fa-solid fa-check-circle": "check_circle",
    "fa-solid fa-info-circle": "info",
    "fa-solid fa-question-circle": "help",
    "fa-solid fa-exclamation-circle": "error",
    "fa-solid fa-thumbtack": "push_pin",
    "fa-solid fa-trophy": "emoji_events",
    "fa-solid fa-medal": "military_tech",
    "fa-solid fa-glasses": "glasses", // Als material symbols gebruikt wordt, anders leeg
    "fa-solid fa-microscope": "biotech",
    "fa-solid fa-balance-scale": "balance",
    "fa-solid fa-briefcase-medical": "medical_services",
    "fa-solid fa-syringe": "vaccines",
    "fa-solid fa-virus": "coronavirus",
    "fa-solid fa-thermometer": "thermostat",
    "fa-solid fa-temperature-low": "ac_unit",
    "fa-solid fa-temperature-high": "wb_sunny",
    "fa-solid fa-water": "water_drop",
    "fa-solid fa-wind": "air",
    "fa-solid fa-smile": "sentiment_satisfied",
    "fa-solid fa-frown": "sentiment_dissatisfied",
    "fa-solid fa-grin": "sentiment_very_satisfied",
    "fa-solid fa-tired": "tired", // Geen directe match
    "fa-solid fa-dizzy": "sick",
    "fa-solid fa-angry": "mood_bad",
    "fa-solid fa-meh": "sentiment_neutral",
    "fa-solid fa-laugh": "mood",
    "fa-solid fa-handshake": "handshake",
    "fa-solid fa-hand-rock": "front_hand",
    "fa-solid fa-hand-paper": "pan_tool",
    "fa-solid fa-hand-scissors": "cut", // Geen exacte hand match
    "fa-solid fa-hand-lizard": "front_hand", // Geen exacte hand match
    "fa-solid fa-hand-spock": "sign_language",
    "fa-solid fa-ghost": "smart_toy", // Geen ghost, alternatief
    "fa-solid fa-alien": "smart_toy",
    "fa-solid fa-robot": "smart_toy",
    "fa-solid fa-space-shuttle": "flight_takeoff",
    "fa-solid fa-car-side": "directions_car",
    "fa-solid fa-bus-alt": "directions_bus_filled",
    "fa-solid fa-truck": "local_shipping",
    "fa-solid fa-motorcycle": "two_wheeler",
    "fa-solid fa-feather": "history_edu",
    "fa-solid fa-snowflake": "ac_unit",
    "fa-solid fa-fire": "local_fire_department",
    "fa-solid fa-bomb": "dangerous",
    "fa-solid fa-fish": "phishing", // Dichtstbijzijnde in symbols
    "fa-solid fa-bone": "pets",
    "fa-solid fa-paw": "pets",
    "fa-solid fa-dove": "flutter_dash",
    "fa-solid fa-dragon": "cruelty_free",
    "fa-solid fa-apple-alt": "nutrition", // Vaak geen specifieke appel
    "fa-solid fa-lemon": "kitchen",
    "fa-solid fa-grapes": "liquor",
    "fa-solid fa-carrot": "restaurant_menu",
    "fa-solid fa-pizza-slice": "local_pizza",
    "fa-solid fa-cocktail": "local_bar",
    "fa-solid fa-beer": "sports_bar",
    "fa-solid fa-wine-bottle": "wine_bar",
    "fa-solid fa-glass-martini": "local_bar",
    "fa-solid fa-glass-cheers": "celebration",
    "fa-solid fa-mug-hot": "coffee",
    "fa-solid fa-pepper-hot": "whatshot",
    "fa-solid fa-utensils": "restaurant",
    "fa-solid fa-birthday-cake": "cake",
    "fa-solid fa-candy-cane": "festival",
    "fa-solid fa-dumbbell": "fitness_center",
    "fa-solid fa-running": "directions_run",
    "fa-solid fa-biking": "pedal_bike",
    "fa-solid fa-swimmer": "pool",
    "fa-solid fa-skiing": "downhill_skiing",
    "fa-solid fa-snowboarding": "snowboarding",
    "fa-solid fa-golf-ball": "golf_course",
    "fa-solid fa-basketball-ball": "sports_basketball",
    "fa-solid fa-football-ball": "sports_football",
    "fa-solid fa-soccer-ball": "sports_soccer",
    "fa-solid fa-baseball-ball": "sports_baseball",
    "fa-solid fa-bowling-ball": "sports",
    "fa-solid fa-chess": "casino", // Geen chess icon

    // Brand Icons (Let op: Google Fonts heeft hier GEEN officiële iconen voor)
    // Ze worden gemapt naar generieke iconen of 'public' als placeholder.
    "fa-brands fa-linkedin": "work",
    "fa-brands fa-facebook": "public",
    "fa-brands fa-twitter": "public",
    "fa-brands fa-instagram": "photo_camera",
    "fa-brands fa-youtube": "smart_display",
    "fa-brands fa-google": "public",
    "fa-brands fa-wikipedia-w": "menu_book",
    "fa-brands fa-github": "code",
    "fa-brands fa-gitlab": "code",
    "fa-brands fa-bitbucket": "code",
    "fa-brands fa-stack-overflow": "question_answer",
    "fa-brands fa-codepen": "data_object",
    "fa-brands fa-slack": "forum",
    "fa-brands fa-discord": "forum",
    "fa-brands fa-skype": "call",
    "fa-brands fa-whatsapp": "chat",
    "fa-brands fa-telegram": "send",
    "fa-brands fa-firefox": "travel_explore",
    "fa-brands fa-chrome": "travel_explore",
    "fa-brands fa-safari": "explore",
    "fa-brands fa-opera": "travel_explore",
    "fa-brands fa-edge": "travel_explore",
    "fa-brands fa-internet-explorer": "travel_explore",
    "fa-brands fa-windows": "desktop_windows",
    "fa-brands fa-apple": "laptop_mac",
    "fa-brands fa-android": "android",
    "fa-brands fa-linux": "terminal",
    "fa-brands fa-ubuntu": "terminal",
    "fa-brands fa-html5": "html",
    "fa-brands fa-python": "terminal"
};

/**
 * Converteert een Font Awesome class string naar een Google Fonts (Material Icons) naam.
 * @param faClass De Font Awesome class (bijv. "fa-solid fa-coffee")
 * @param fallback De standaard icoon naam als de class niet gevonden is
 * @returns De naam van het Google icoon (bijv. "local_cafe")
 */
export function convertFaToGoogleFont(faClass: string, fallback: string = "help_outline"): string {
    // Verwijder extra spaties mochten die aanwezig zijn
    const cleanClass = faClass.trim();

    return faToGoogleMap[cleanClass] || fallback;
}