export const materialIconsList: { icon: string; label: string }[] = [
    // Navigatie & UI
    { icon: "home", label: "Home" },
    { icon: "search", label: "Zoeken" },
    { icon: "settings", label: "Instellingen" },
    { icon: "menu", label: "Menu" },
    { icon: "close", label: "Sluiten" },
    { icon: "check", label: "Vinkje" },
    { icon: "add", label: "Toevoegen" },
    { icon: "remove", label: "Verwijderen" },
    { icon: "delete", label: "Prullenbak" },
    { icon: "edit", label: "Bewerken" },
    { icon: "more_vert", label: "Meer opties (Verticaal)" },
    { icon: "more_horiz", label: "Meer opties (Horizontaal)" },
    { icon: "arrow_back", label: "Pijl Terug" },
    { icon: "arrow_forward", label: "Pijl Volgende" },
    { icon: "arrow_upward", label: "Pijl Omhoog" },
    { icon: "arrow_downward", label: "Pijl Omlaag" },
    { icon: "refresh", label: "Vernieuwen" },
    { icon: "zoom_in", label: "Inzoomen" },
    { icon: "zoom_out", label: "Uitzoomen" },

    // Gebruikers & Communicatie
    { icon: "person", label: "Gebruiker" },
    { icon: "person_add", label: "Gebruiker toevoegen" },
    { icon: "group", label: "Groep / Team" },
    { icon: "mail", label: "E-mail" },
    { icon: "call", label: "Telefoon" },
    { icon: "chat", label: "Chat" },
    { icon: "forum", label: "Forum / Discussie" },
    { icon: "send", label: "Verzenden" },
    { icon: "notifications", label: "Notificaties" },
    { icon: "share", label: "Delen" },
    { icon: "thumb_up", label: "Duim omhoog" },
    { icon: "thumb_down", label: "Duim omlaag" },

    // Media, Bestanden & IT
    { icon: "photo_camera", label: "Camera" },
    { icon: "image", label: "Afbeelding" },
    { icon: "videocam", label: "Video" },
    { icon: "mic", label: "Microfoon" },
    { icon: "volume_up", label: "Volume aan" },
    { icon: "volume_off", label: "Volume uit" },
    { icon: "music_note", label: "Muziek" },
    { icon: "folder", label: "Map" },
    { icon: "folder_open", label: "Map open" },
    { icon: "insert_drive_file", label: "Document" },
    { icon: "cloud", label: "Cloud" },
    { icon: "cloud_upload", label: "Uploaden" },
    { icon: "cloud_download", label: "Downloaden" },
    { icon: "attach_file", label: "Bijlage" },
    { icon: "code", label: "Code" },
    { icon: "terminal", label: "Terminal / Console" },
    { icon: "bug_report", label: "Bug / Fout" },

    // Tekst & Opmaak (Handig voor een editor)
    { icon: "format_bold", label: "Vetgedrukt" },
    { icon: "format_italic", label: "Cursief" },
    { icon: "format_underlined", label: "Onderstreept" },
    { icon: "format_list_bulleted", label: "Opsommingstekens" },
    { icon: "format_list_numbered", label: "Genummerde lijst" },
    { icon: "format_align_left", label: "Links uitlijnen" },
    { icon: "format_align_center", label: "Centreren" },
    { icon: "format_align_right", label: "Rechts uitlijnen" },
    { icon: "link", label: "Link" },
    { icon: "link_off", label: "Link verwijderen" },
    { icon: "title", label: "Titel / Koptekst" },

    // Acties, Statussen & Veiligheid
    { icon: "favorite", label: "Favoriet / Hartje" },
    { icon: "favorite_border", label: "Hartje (leeg)" },
    { icon: "star", label: "Ster" },
    { icon: "star_border", label: "Ster (leeg)" },
    { icon: "star_half", label: "Ster (half)" },
    { icon: "info", label: "Informatie" },
    { icon: "help", label: "Help / Vraagteken" },
    { icon: "warning", label: "Waarschuwing" },
    { icon: "error", label: "Foutmelding" },
    { icon: "lock", label: "Slot (Dicht)" },
    { icon: "lock_open", label: "Slot (Open)" },
    { icon: "shield", label: "Schild / Veiligheid" },
    { icon: "gavel", label: "Rechtspraak / Hamer" },

    // E-commerce, Financiën & Werk
    { icon: "shopping_cart", label: "Winkelwagen" },
    { icon: "shopping_bag", label: "Winkeltas" },
    { icon: "credit_card", label: "Creditcard" },
    { icon: "payments", label: "Betaling / Cash" },
    { icon: "monetization_on", label: "Geld / Munt" },
    { icon: "account_balance", label: "Bank / Instituut" },
    { icon: "savings", label: "Spaarvarken" },
    { icon: "receipt", label: "Bon / Factuur" },
    { icon: "store", label: "Winkel" },
    { icon: "work", label: "Werk / Koffer" },
    { icon: "calendar_today", label: "Kalender" },
    { icon: "event", label: "Evenement" },
    { icon: "schedule", label: "Klok / Tijd" },

    // Transport & Logistiek
    { icon: "flight", label: "Vliegtuig" },
    { icon: "directions_car", label: "Auto" },
    { icon: "directions_bus", label: "Bus" },
    { icon: "train", label: "Trein" },
    { icon: "directions_bike", label: "Fiets" },
    { icon: "local_shipping", label: "Vrachtwagen / Levering" },
    { icon: "sailing", label: "Zeilboot" },
    { icon: "two_wheeler", label: "Motor / Scooter" },

    // Natuur & Weer
    { icon: "wb_sunny", label: "Zon" },
    { icon: "dark_mode", label: "Maan / Donker" },
    { icon: "ac_unit", label: "Sneeuwvlok / Airco" },
    { icon: "water_drop", label: "Waterdruppel" },
    { icon: "air", label: "Wind" },
    { icon: "park", label: "Boom / Park" },
    { icon: "forest", label: "Bos" },
    { icon: "eco", label: "Blad / Duurzaamheid" },

    // Plaatsen & Apparaten
    { icon: "place", label: "Locatie (Pin)" },
    { icon: "map", label: "Kaart" },
    { icon: "public", label: "Wereldbol" },
    { icon: "smartphone", label: "Mobiel" },
    { icon: "computer", label: "Computer" },
    { icon: "laptop_mac", label: "Laptop" },
    { icon: "print", label: "Printen" },

    // Overig, Horeca & Gezondheid
    { icon: "lightbulb", label: "Idee / Lamp" },
    { icon: "local_cafe", label: "Koffie" },
    { icon: "restaurant", label: "Restaurant / Bestek" },
    { icon: "local_pizza", label: "Pizza" },
    { icon: "local_bar", label: "Drankje" },
    { icon: "fitness_center", label: "Sporten / Halter" },
    { icon: "medical_services", label: "Medische koffer" },
    { icon: "science", label: "Wetenschap / Beker" },
    { icon: "visibility", label: "Oog (Zichtbaar)" },
    { icon: "visibility_off", label: "Oog (Verborgen)" },
    { icon: "emoji_events", label: "Trofee" },
    { icon: "workspace_premium", label: "Medaille / Premium" },
    { icon: "sentiment_satisfied", label: "Blij gezicht" },
    { icon: "sentiment_dissatisfied", label: "Verdrietig gezicht" },

    // Extra iconen uit de Font Awesome-conversie
    { icon: "anchor", label: "Anker" },
    { icon: "android", label: "Android" },
    { icon: "audio_file", label: "Audiobestand" },
    { icon: "balance", label: "Balans" },
    { icon: "bar_chart", label: "Staafdiagram" },
    { icon: "beach_access", label: "Strandtoegang" },
    { icon: "biotech", label: "Biotechnologie" },
    { icon: "bolt", label: "Bliksem" },
    { icon: "brush", label: "Penseel" },
    { icon: "cake", label: "Taart" },
    { icon: "cancel", label: "Annuleren" },
    { icon: "casino", label: "Casino" },
    { icon: "celebration", label: "Feest" },
    { icon: "check_circle", label: "Controlecirkel" },
    { icon: "coffee", label: "Koffie" },
    { icon: "comment", label: "Opmerking" },
    { icon: "content_copy", label: "Kopiëren" },
    { icon: "content_cut", label: "Knippen" },
    { icon: "content_paste", label: "Plakken" },
    { icon: "coronavirus", label: "Coronavirus" },
    { icon: "cruelty_free", label: "Dierenvriendelijk" },
    { icon: "cut", label: "Knippen" },
    { icon: "dangerous", label: "Gevaarlijk" },
    { icon: "data_object", label: "Data object" },
    { icon: "description", label: "Beschrijving" },
    { icon: "desktop_windows", label: "Desktop" },
    { icon: "directions_boat", label: "Boot" },
    { icon: "directions_bus_filled", label: "Bus gevuld" },
    { icon: "directions_run", label: "Rennen" },
    { icon: "downhill_skiing", label: "Bergskiën" },
    { icon: "explore", label: "Verkennen" },
    { icon: "festival", label: "Festival" },
    { icon: "flight_takeoff", label: "Vertrekken" },
    { icon: "flutter_dash", label: "Flutter" },
    { icon: "folder_zip", label: "Map zip" },
    { icon: "format_align_justify", label: "Volledig uitlijnen" },
    { icon: "format_indent_decrease", label: "Inspringing verkleinen" },
    { icon: "format_indent_increase", label: "Inspringing vergroten" },
    { icon: "format_quote", label: "Citaat" },
    { icon: "format_strikethrough", label: "Doorhalen" },
    { icon: "front_hand", label: "Hand" },
    { icon: "glasses", label: "Bril" },
    { icon: "golf_course", label: "Golfbaan" },
    { icon: "grid_on", label: "Raster" },
    { icon: "handshake", label: "Handdruk" },
    { icon: "history_edu", label: "Geschiedenis" },
    { icon: "hourglass_empty", label: "Zandloper" },
    { icon: "html", label: "HTML" },
    { icon: "integration_instructions", label: "Integratie" },
    { icon: "key", label: "Sleutel" },
    { icon: "kitchen", label: "Keuken" },
    { icon: "light_mode", label: "Lichtmodus" },
    { icon: "liquor", label: "Alcohol" },
    { icon: "list", label: "Lijst" },
    { icon: "local_fire_department", label: "Brandweer" },
    { icon: "menu_book", label: "Boekmenu" },
    { icon: "military_tech", label: "Militair" },
    { icon: "mood", label: "Stemming" },
    { icon: "mood_bad", label: "Slechte stemming" },
    { icon: "nutrition", label: "Voeding" },
    { icon: "pan_tool", label: "Hulp" },
    { icon: "pedal_bike", label: "Fiets" },
    { icon: "pets", label: "Dieren" },
    { icon: "phishing", label: "Phishing" },
    { icon: "picture_as_pdf", label: "PDF" },
    { icon: "pie_chart", label: "Taartdiagram" },
    { icon: "pool", label: "Zwembad" },
    { icon: "push_pin", label: "Pin" },
    { icon: "question_answer", label: "Vraag en antwoord" },
    { icon: "redeem", label: "Inwisselen" },
    { icon: "restaurant_menu", label: "Menu" },
    { icon: "rocket_launch", label: "Raket" },
    { icon: "sentiment_neutral", label: "Neutraal" },
    { icon: "sentiment_very_satisfied", label: "Zeer tevreden" },
    { icon: "set_meal", label: "Maaltijd" },
    { icon: "show_chart", label: "Grafiek" },
    { icon: "sick", label: "Ziek" },
    { icon: "sign_language", label: "Gebarentaal" },
    { icon: "slideshow", label: "Diavoorstelling" },
    { icon: "smart_display", label: "Smart display" },
    { icon: "smart_toy", label: "Smart toy" },
    { icon: "snowboarding", label: "Snowboarden" },
    { icon: "sports", label: "Sport" },
    { icon: "sports_bar", label: "Sportbar" },
    { icon: "sports_baseball", label: "Baseball" },
    { icon: "sports_basketball", label: "Basketbal" },
    { icon: "sports_esports", label: "E-sports" },
    { icon: "sports_football", label: "Voetbal" },
    { icon: "sports_soccer", label: "Voetbal" },
    { icon: "table_chart", label: "Tabel" },
    { icon: "thermostat", label: "Thermostaat" },
    { icon: "tired", label: "Moe" },
    { icon: "travel_explore", label: "Reizen" },
    { icon: "tv", label: "Tv" },
    { icon: "umbrella", label: "Paraplu" },
    { icon: "vaccines", label: "Vaccins" },
    { icon: "video_file", label: "Videobestand" },
    { icon: "whatshot", label: "Whotshot" },
    { icon: "wine_bar", label: "Wijnbar" }
];